# Generated by Django 4.2.3 on 2023-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Table_Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
