# Generated by Django 4.2.3 on 2023-09-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_image', models.FileField(default=None, null=True, upload_to='Chefs')),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_designation', models.CharField(max_length=100)),
                ('chef_someline', models.TextField()),
                ('chef_twitter', models.URLField()),
                ('chef_facebook', models.URLField()),
                ('chef_instagram', models.URLField()),
                ('chef_linkedin', models.URLField()),
            ],
        ),
    ]
