# Generated by Django 4.2.3 on 2023-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHEFS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefs',
            name='chef_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='chef_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='chef_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='chef_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
