# Generated by Django 4.2.3 on 2023-08-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast_img', models.ImageField(default='starter_image.png', upload_to='static/images/menu/breakfast')),
                ('breakfast_title', models.CharField(max_length=50)),
                ('breakfast_decprition', models.TextField(max_length=100)),
                ('breakfast_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_img', models.ImageField(default='starter_image.png', upload_to='static/images/menu/dinner')),
                ('dinner_title', models.CharField(max_length=50)),
                ('dinner_decprition', models.TextField(max_length=100)),
                ('dinner_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch_img', models.ImageField(default='starter_image.png', upload_to='static/images/menu/lunch')),
                ('lunch_title', models.CharField(max_length=50)),
                ('lunch_decprition', models.TextField(max_length=100)),
                ('lunch_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_img', models.ImageField(default='starter_image.png', upload_to='static/images/menu/starter')),
                ('starter_title', models.CharField(max_length=50)),
                ('starter_decprition', models.TextField(max_length=100)),
                ('starter_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
