# Generated by Django 4.2.3 on 2023-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='breakfast_img',
            field=models.FileField(default=None, upload_to='menu/breakfast'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='dinner_img',
            field=models.FileField(default=None, upload_to='menu/dinner'),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='lunch_img',
            field=models.FileField(default=None, upload_to='menu/lunch'),
        ),
        migrations.AlterField(
            model_name='starter',
            name='starter_img',
            field=models.FileField(default=None, upload_to='menu/starter'),
        ),
    ]
