# Generated by Django 4.2.3 on 2023-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_quets', models.TextField(max_length=300)),
                ('test_name', models.CharField(max_length=50)),
                ('test_designation', models.TextField(max_length=100)),
                ('test_image', models.ImageField(default='testimonials_image.jpg', upload_to='static/images/testimonials')),
            ],
        ),
    ]
