# Generated by Django 4.2.3 on 2023-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='test_image',
            field=models.FileField(default=None, null=True, upload_to='testimonials'),
        ),
    ]
